### ISSUE TITLE
cuda initialisation fails with exception, when using Go 1.5

### ISSUE THREAD

**Issue by angusr** [barnex/cuda5#2]
Hi,
Using Go 1.4.2, I'm able to successfully initialise CUDA using cu.Init(0). However, when the 64 bit app, built using Go 1.5 on Windows, is run, an exception is generated with this trace:

```
Exception 0xc0000005 0x0 0xbf1abe 0x5d84b0
PC=0x5d84b0
signal arrived during external code execution

github.com/barnex/cuda5/cu._Cfunc_cuInit(0x0, 0x0)
        ??:0 +0x3c
github.com/barnex/cuda5/cu.Init(0x0)
        c:/Go/src/github.com/barnex/cuda5/cu/init.go:12 +0x29
main.main()
        c:/projects/src/github.com/cuda/main.go:45 +0x107

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1696 +0x1
rax     0x0
rbx     0xc08202fe40
rcx     0x0
rdi     0xc08202fe40
rsi     0x5f0000
rbp     0x24fdc0
rsp     0x24fd78
r8      0xc08201a000
r9      0xc08202fdd0
r10     0xc082032f28
r11     0xc082032ea0
r12     0x1a
r13     0x5748f8
r14     0xf
r15     0x8
rip     0x5d84b0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

I'd searched for any CGO-specific issues with 1.5, but didn't find anything.
Do you have any ideas?

**Comment by barnex** [comment]
This has, I believe, occurred once with some go 1.x.0 release and magically
disappeared the next minor release. So I would wait for Go 1.5.1 and see
what happens.

**Comment by godsic** [comment]
MuMax3 (that uses barnex/cuda5 internally) works just fine with go1.5.1. So I guess this issue could be  closed now as 'resovled upstream'.

**Comment by barnex** [comment]
Thanks @godsic. @angusr, can you confirm this?

**Comment by barnex** [comment]
resovled upstream
