### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by odeke-em** [barnex/cuda5#3]
Hello there @barnex, thank you for the work on this repo.

I kindly wanted to ask if you might have some simple examples for users to get started with the packages in this repo. I think that would be useful.

Thank you.

**Comment by barnex** [comment]
Hi. These packages were designed for use by https://mumax.github.io. See, e.g.: https://github.com/mumax/3/tree/master/cuda for canonical usage. The unit tests also show how to use it, e.g.: https://github.com/mumax/3/blob/master/cuda/cufft/fft_test.go.

There is also this talk available: https://fosdem.org/2014/schedule/event/hpc_devroom_go.

Finally, note that this package interacts with CUDA's low-level API, so do not expect things to be super easy.

**Comment by odeke-em** [comment]
Thank you for the response. Yap, I checked out your talk which is what got me interested. Aye aye, I'll look at the tests as well as through more of the code. Thanks again.
